Performing Web/Internet Transactions
------------------------------------

The curl module is used to create and perform web transactions like HTTP
requests, FTP transfers etc.

curl implements the cURL easy interface described at
http://curl.haxx.se/libcurl/c/libcurl-easy.html and the cURL multi
interface. Constants defined by the C interface are mapped to Lua in the
following way:

CURLE_NAMED becomes curl.NAME etc.

The typical use is to create a curl session, set the options (i.e. what
type of transfer it is, the URL, any data etc.) and then to perform the
session.

Creating and performing requests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

easy()
^^^^^^

Create a new curl session using the cURL easy interface.

req:setopt(option, value)
^^^^^^^^^^^^^^^^^^^^^^^^^

Set a curl option.

req:getinfo(code)
^^^^^^^^^^^^^^^^^

Request internal information from the curl session.

req:perform()
^^^^^^^^^^^^^

Perform the request.

req:close()
^^^^^^^^^^^

Close the curl session.

Escaping and unescaping of URL strings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

escape(string)
^^^^^^^^^^^^^^

Escape string for use in a URL.

unescape(sting)
^^^^^^^^^^^^^^^

Unescape the URL-escaped string parameter.
